### ISSUE TITLE
Great project - A question please.

### ISSUE THREAD

**Issue by waelsaad** [tesseract-one/Bip39.swift#1]
Hi, Thank you for this library. I am just trying to get my head around something please, I hope you can help me understand :). 

What is the advantage of using this wrapper UncommonCrypto for the alternative C implementation for Linux ? as oppose to the following implementation where I've come across couple of libraries that are doing things directly in Swift using a methond **PBKDF2SHA512** implemented in **PKCS5** such as 
https://github.com/pengpengliu/BIP39
and 
https://github.com/zcash-hackworks/MnemonicSwift

Thank you,

Wael

**Comment by ypopovych** [comment]
Hi.
CommonCrypto framework is an Apple framework.
Swift on Linux doesn't have it.
That's why we created our own "UncommonCrypto".  It uses CommonCrypto on the Apple platforms and provides C-based implementations on Linux.

**Comment by waelsaad** [comment]
Thank you for clarification.
